use super::*;

impl MainWindow {
    pub fn new<
        TSecret,
        TVault,
        TUser,
        TAdmin,
        TTeam,
        TTotp,
        TPolicy,
        TBackup,
        TBackupApp,
        TImport,
    >(
        application: &adw::Application,
        runtime_handle: Handle,
        secret_service: Arc<TSecret>,
        vault_service: Arc<TVault>,
        user_service: Arc<TUser>,
        admin_service: Arc<TAdmin>,
        team_service: Arc<TTeam>,
        totp_service: Arc<TTotp>,
        auth_policy_service: Arc<TPolicy>,
        backup_service: Arc<TBackup>,
        backup_app_service: Arc<TBackupApp>,
        import_service: Arc<TImport>,
        #[cfg(feature = "premium")] license_service: Arc<LicenseService>,
        database_pool: SqlitePool,
        database_path: PathBuf,
        admin_user_id: Uuid,
        admin_master_key: Vec<u8>,
        connected_identity_label: String,
        license_badge_text: String,
        is_admin: bool,
    ) -> Self
    where
        TSecret: SecretService + Send + Sync + 'static,
        TVault: VaultService + Send + Sync + 'static,
        TUser: UserService + Send + Sync + 'static,
        TAdmin: AdminService + Send + Sync + 'static,
        TTeam: TeamService + Send + Sync + 'static,
        TTotp: TotpService + Send + Sync + 'static,
        TPolicy: AuthPolicyService + Send + Sync + 'static,
        TBackup: BackupService + Send + Sync + 'static,
        TBackupApp: BackupApplicationService + Send + Sync + 'static,
        TImport: ImportService + Send + Sync + 'static,
    {
        window::core::build_main_window(
            application,
            runtime_handle,
            secret_service,
            vault_service,
            user_service,
            admin_service,
            team_service,
            totp_service,
            auth_policy_service,
            backup_service,
            backup_app_service,
            import_service,
            #[cfg(feature = "premium")]
            license_service,
            database_pool,
            database_path,
            admin_user_id,
            admin_master_key,
            connected_identity_label,
            license_badge_text,
            is_admin,
        )
    }
}
