#!/usr/bin/env bash
# scripts/collect-dlls.sh
# Generates wix/dlls.wxs from the DLL dependency graph of heelonvault.exe for GTK4.
set -euo pipefail

BINARY=""
MSYS2_ROOT="/mingw64"
STAGING_DIR="wix/staging"
OUT_WXS="wix/dlls.wxs"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --binary)   BINARY="$2";      shift 2 ;;
    --msys2)    MSYS2_ROOT="$2";  shift 2 ;;
    --staging)  STAGING_DIR="$2"; shift 2 ;;
    --out)      OUT_WXS="$2";     shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

[[ -z "$BINARY" ]] && { echo "[ERROR] --binary is required"; exit 1; }
[[ -f "$BINARY" ]] || { echo "[ERROR] Binary not found: $BINARY"; exit 1; }

echo "[collect-dlls] Binary : $BINARY"
echo "[collect-dlls] MSYS2  : $MSYS2_ROOT"
echo "[collect-dlls] Staging: $STAGING_DIR"
echo "[collect-dlls] Output : $OUT_WXS"

# ── 1. Collect transitive DLLs via ntldd ─────────────────────────────────────
echo "[collect-dlls] Running ntldd..."
DLL_PATHS=$(ntldd -R "$BINARY" \
  | grep -i "mingw64" \
  | awk -F'=>' '{print $2}' | awk '{print $1}' \
  | sort -u | while IFS= read -r p; do cygpath -u "$p" 2>/dev/null || echo "$p"; done)

# Ajouter manuellement les DLLs critiques pour GTK4 (au cas où ntldd ne les détecte pas)
GTK4_DLLS=(
  "$MSYS2_ROOT/bin/libgtk-4-1.dll"
  "$MSYS2_ROOT/bin/libgraphene-1.0-0.dll"
  "$MSYS2_ROOT/bin/libepoxy-0.dll"
)

# Fusionner les listes
DLL_PATHS=$(echo -e "$DLL_PATHS\n$(printf "%s\n" "${GTK4_DLLS[@]}")" | sort -u)

DLL_COUNT=$(echo "$DLL_PATHS" | grep -c . || true)
echo "[collect-dlls] Found $DLL_COUNT DLLs to bundle"

# ── 2. Stage DLLs ────────────────────────────────────────────────────────────
mkdir -p "$STAGING_DIR"
mkdir -p "$STAGING_DIR/lib/gdk-pixbuf-2.0/2.10.0/loaders"

echo "$DLL_PATHS" | while IFS= read -r dll_path; do
  [[ -z "$dll_path" ]] && continue
  [[ -f "$dll_path" ]] || { echo "[WARNING] DLL not found: $dll_path"; continue; }
  dll_name=$(basename "$dll_path")
  cp "$dll_path" "$STAGING_DIR/"
  echo "[collect-dlls] Staged: $dll_name"
done

# ── 3. Copy GDK-Pixbuf loaders (si toujours utilisé) ────────────────────────
if [[ -d "$MSYS2_ROOT/lib/gdk-pixbuf-2.0/2.10.0/loaders" ]]; then
  cp "$MSYS2_ROOT/lib/gdk-pixbuf-2.0/2.10.0/loaders"/*.dll "$STAGING_DIR/lib/gdk-pixbuf-2.0/2.10.0/loaders/" || true
  cp "$MSYS2_ROOT/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache" "$STAGING_DIR/lib/gdk-pixbuf-2.0/2.10.0/" || true
fi

# ── 4. Copy GTK4 theme assets ────────────────────────────────────────────
mkdir -p "$STAGING_DIR/share/themes/Adwaita"
if [[ -d "$MSYS2_ROOT/share/themes/Adwaita" ]]; then
  cp -r "$MSYS2_ROOT/share/themes/Adwaita"/* "$STAGING_DIR/share/themes/Adwaita/" || true
else
  echo "[WARNING] Theme source not found: $MSYS2_ROOT/share/themes/Adwaita — GTK4 theme will be missing"
fi

# ── 4bis. Copy Adwaita icon theme (required by libadwaita for symbolic icons) ──
mkdir -p "$STAGING_DIR/share/icons/Adwaita"
if [[ -d "$MSYS2_ROOT/share/icons/Adwaita" ]]; then
  cp -r "$MSYS2_ROOT/share/icons/Adwaita"/* "$STAGING_DIR/share/icons/Adwaita/" || true
else
  echo "[WARNING] Icon theme source not found: $MSYS2_ROOT/share/icons/Adwaita — app icons may be blank"
fi

# ── 4ter. Copy SQL migrations (single source of truth: repo migrations/) ──
mkdir -p "$STAGING_DIR/migrations"
if [[ -d "migrations" ]]; then
  cp migrations/*.sql "$STAGING_DIR/migrations/" 2>/dev/null || true
  echo "[collect-dlls] Staged $(find "$STAGING_DIR/migrations" -maxdepth 1 -name '*.sql' | wc -l) migration file(s)"
else
  echo "[WARNING] migrations/ not found — run this script from the repo root"
fi

# ── 5. Compile GLib schemas ────────────────────────────────────────────────
echo "[collect-dlls] Compiling GLib schemas..."
mkdir -p "$STAGING_DIR/share/glib-2.0/schemas"
glib-compile-schemas "$MSYS2_ROOT/share/glib-2.0/schemas" \
  --targetdir="$STAGING_DIR/share/glib-2.0/schemas"
echo "[collect-dlls] gschemas.compiled generated"

# ── 6. Generate heelonvault.ico from PNG ──────────────────────────────────
ICON_SRC="assets/icons/hicolor/256x256/apps/heelonvault.png"
if [[ -f "$ICON_SRC" ]]; then
  magick "$ICON_SRC" \
    -define icon:auto-resize=256,128,64,48,32,16 \
    "$STAGING_DIR/heelonvault.ico"
  echo "[collect-dlls] Icon staged: heelonvault.ico"
else
  echo "[WARNING] Icon source not found: $ICON_SRC — WiX build will fail"
fi

# ── 7. loaders.cache fallback ─────────────────────────────────────────────
if [[ ! -s "$STAGING_DIR/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache" ]]; then
  echo "[collect-dlls] loaders.cache absent/empty — generating via gdk-pixbuf-query-loaders"
  gdk-pixbuf-query-loaders > "$STAGING_DIR/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache" || true
fi

# ── 8. Generate WXS file ───────────────────────────────────────────────────
sanitize_wix_id() {
  echo "$1" | tr - _ | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9_]//g'
}

# Header
mkdir -p "$(dirname "$OUT_WXS")"
cat > "$OUT_WXS" << 'WXSHEADER'
<!--
  AUTO-GENERATED by scripts/collect-dlls.sh — DO NOT EDIT MANUALLY
  Regenerate by running the script in a MSYS2 MINGW64 shell.
-->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <ComponentGroup Id="DllComponents" Directory="INSTALLFOLDER">
WXSHEADER

# DLL Components
INDEX=0
echo "$DLL_PATHS" | while IFS= read -r dll_path; do
  [[ -z "$dll_path" ]] && continue
  [[ -f "$STAGING_DIR/$(basename "$dll_path")" ]] || continue
  dll_name=$(basename "$dll_path")
  safe_name="$(sanitize_wix_id "$dll_name")"
  safe_id="Dll_${safe_name}_$INDEX"
  guid=$(python3 -c "import uuid; print(str(uuid.uuid5(uuid.NAMESPACE_DNS, '${dll_name}')).upper())" 2>/dev/null || uuidgen | tr '[:lower:]' '[:upper:]')
  cat >> "$OUT_WXS" << DLLCOMP
      <Component Id="${safe_id}" Guid="${guid}">
        <File Id="file_${safe_id}"
              Source="wix\\staging\\${dll_name}"
              KeyPath="yes" />
      </Component>
DLLCOMP
  INDEX=$((INDEX + 1))
done

# GDK-Pixbuf loaders
cat >> "$OUT_WXS" << 'PIXBUFHEADER'
    </ComponentGroup>

    <ComponentGroup Id="PixbufLoaderComponents" Directory="GDKPIXBUF_LOADERS_DIR">
PIXBUFHEADER

PINDEX=0
for loader_dll in "$STAGING_DIR/lib/gdk-pixbuf-2.0/2.10.0/loaders"/*.dll; do
  [[ -f "$loader_dll" ]] || continue
  pname=$(basename "$loader_dll")
  safe_pname="$(sanitize_wix_id "$pname")"
  safe_pid="Pixbuf_${safe_pname}_$PINDEX"
  pguid=$(python3 -c "import uuid; print(str(uuid.uuid5(uuid.NAMESPACE_DNS, 'pixbuf_${pname}')).upper())" 2>/dev/null || uuidgen | tr '[:lower:]' '[:upper:]')
  cat >> "$OUT_WXS" << PIXBUFCOMP
      <Component Id="${safe_pid}" Guid="${pguid}">
        <File Id="file_${safe_pid}"
              Source="wix\\staging\\lib\\gdk-pixbuf-2.0\\2.10.0\\loaders\\${pname}"
              KeyPath="yes" />
      </Component>
PIXBUFCOMP
  PINDEX=$((PINDEX + 1))
done

# GTK4 theme (Adwaita) — one Component per staged file, nested dirs via Subdirectory
cat >> "$OUT_WXS" << 'THEMEHEADER'
    </ComponentGroup>

    <ComponentGroup Id="GTK4ThemeComponents" Directory="ADWAITAFOLDER">
THEMEHEADER

TINDEX=0
THEME_ROOT="$STAGING_DIR/share/themes/Adwaita"
if [[ -d "$THEME_ROOT" ]]; then
  while IFS= read -r -d '' theme_file; do
    rel_path="${theme_file#"$THEME_ROOT/"}"
    rel_dir="$(dirname "$rel_path")"
    safe_id="Theme_$TINDEX"
    guid=$(python3 -c "import uuid; print(str(uuid.uuid5(uuid.NAMESPACE_DNS, 'theme_${rel_path}')).upper())" 2>/dev/null || uuidgen | tr '[:lower:]' '[:upper:]')
    win_source="wix\\staging\\share\\themes\\Adwaita\\${rel_path//\//\\}"
    if [[ "$rel_dir" == "." ]]; then
      printf '      <Component Id="%s" Guid="%s">\n        <File Id="file_%s" Source="%s" KeyPath="yes" />\n      </Component>\n' \
        "$safe_id" "$guid" "$safe_id" "$win_source" >> "$OUT_WXS"
    else
      printf '      <Component Id="%s" Guid="%s" Subdirectory="%s">\n        <File Id="file_%s" Source="%s" KeyPath="yes" />\n      </Component>\n' \
        "$safe_id" "$guid" "${rel_dir//\//\\}" "$safe_id" "$win_source" >> "$OUT_WXS"
    fi
    TINDEX=$((TINDEX + 1))
  done < <(find "$THEME_ROOT" -type f -print0 | sort -z)
fi
echo "[collect-dlls] Staged $TINDEX GTK4 theme file(s)"

# Adwaita icon theme — same pattern, deep nesting (sizes/categories)
cat >> "$OUT_WXS" << 'ICONHEADER'
    </ComponentGroup>

    <ComponentGroup Id="IconComponents" Directory="ADWAITAICONSFOLDER">
ICONHEADER

IINDEX=0
ICON_ROOT="$STAGING_DIR/share/icons/Adwaita"
if [[ -d "$ICON_ROOT" ]]; then
  while IFS= read -r -d '' icon_file; do
    rel_path="${icon_file#"$ICON_ROOT/"}"
    rel_dir="$(dirname "$rel_path")"
    safe_id="Icon_$IINDEX"
    guid=$(python3 -c "import uuid; print(str(uuid.uuid5(uuid.NAMESPACE_DNS, 'icon_${rel_path}')).upper())" 2>/dev/null || uuidgen | tr '[:lower:]' '[:upper:]')
    win_source="wix\\staging\\share\\icons\\Adwaita\\${rel_path//\//\\}"
    if [[ "$rel_dir" == "." ]]; then
      printf '      <Component Id="%s" Guid="%s">\n        <File Id="file_%s" Source="%s" KeyPath="yes" />\n      </Component>\n' \
        "$safe_id" "$guid" "$safe_id" "$win_source" >> "$OUT_WXS"
    else
      printf '      <Component Id="%s" Guid="%s" Subdirectory="%s">\n        <File Id="file_%s" Source="%s" KeyPath="yes" />\n      </Component>\n' \
        "$safe_id" "$guid" "${rel_dir//\//\\}" "$safe_id" "$win_source" >> "$OUT_WXS"
    fi
    IINDEX=$((IINDEX + 1))
  done < <(find "$ICON_ROOT" -type f -print0 | sort -z)
fi
echo "[collect-dlls] Staged $IINDEX Adwaita icon file(s)"

# SQL migrations — generated from staged migrations/ (no manual list to maintain)
cat >> "$OUT_WXS" << 'MIGHEADER'
    </ComponentGroup>

    <ComponentGroup Id="MigrationsComponents" Directory="MIGRATIONSFOLDER">
MIGHEADER

MINDEX=0
if [[ -d "$STAGING_DIR/migrations" ]]; then
  while IFS= read -r -d '' mig_file; do
    fname=$(basename "$mig_file")
    safe_id="Mig_$MINDEX"
    guid=$(python3 -c "import uuid; print(str(uuid.uuid5(uuid.NAMESPACE_DNS, 'migration_${fname}')).upper())" 2>/dev/null || uuidgen | tr '[:lower:]' '[:upper:]')
    printf '      <Component Id="%s" Guid="%s">\n        <File Id="file_%s" Source="wix\\staging\\migrations\\%s" KeyPath="yes" />\n      </Component>\n' \
      "$safe_id" "$guid" "$safe_id" "$fname" >> "$OUT_WXS"
    MINDEX=$((MINDEX + 1))
  done < <(find "$STAGING_DIR/migrations" -maxdepth 1 -type f -name '*.sql' -print0 | sort -z)
fi
if [[ "$MINDEX" -eq 0 ]]; then
  echo "[WARNING] No .sql migration staged — MSI will ship without migrations"
fi
echo "[collect-dlls] Staged $MINDEX migration component(s)"

# Footer
cat >> "$OUT_WXS" << 'WXSFOOTER'
    </ComponentGroup>
  </Fragment>
</Wix>
WXSFOOTER

echo "[collect-dlls] Done — $OUT_WXS written."