#!/usr/bin/env bash
# scripts/collect-dlls.sh
# ─────────────────────────────────────────────────────────────────────────────
# Generates wix/dlls.wxs from the DLL dependency graph of heelonvault.exe.
#
# Usage (inside MSYS2 MINGW64 shell):
#   bash scripts/collect-dlls.sh \
#       --binary   target/release/heelonvault.exe \
#       --msys2    /mingw64 \
#       --staging  wix/staging \
#       --out      wix/dlls.wxs
#
# Requires: ntldd (mingw-w64-x86_64-ntldd), ImageMagick (for .ico conversion)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

BINARY=""
MSYS2_ROOT="/mingw64"
STAGING_DIR="wix/staging"
OUT_WXS="wix/dlls.wxs"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --binary)   BINARY="$2";      shift 2 ;;
    --msys2)    MSYS2_ROOT="$2";  shift 2 ;;
    --staging)  STAGING_DIR="$2"; shift 2 ;;
    --out)      OUT_WXS="$2";     shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

[[ -z "$BINARY" ]] && { echo "[ERROR] --binary is required"; exit 1; }
[[ -f "$BINARY" ]] || { echo "[ERROR] Binary not found: $BINARY"; exit 1; }

echo "[collect-dlls] Binary : $BINARY"
echo "[collect-dlls] MSYS2  : $MSYS2_ROOT"
echo "[collect-dlls] Staging: $STAGING_DIR"
echo "[collect-dlls] Output : $OUT_WXS"

# ── 1. Collect transitive DLLs via ntldd ─────────────────────────────────────
echo "[collect-dlls] Running ntldd..."
# ntldd -R prints full recursive dependency tree; filter lines that contain the
# MSYS2 mingw path, strip whitespace, extract the path token.
DLL_PATHS=$(ntldd -R "$BINARY" \
  | grep -i "mingw64" \
  | awk '{print $3}' \
  | sort -u)

DLL_COUNT=$(echo "$DLL_PATHS" | grep -c . || true)
echo "[collect-dlls] Found $DLL_COUNT DLLs to bundle"

# ── 2. Stage DLLs ────────────────────────────────────────────────────────────
mkdir -p "$STAGING_DIR"
DLL_STAGING="$STAGING_DIR"

echo "$DLL_PATHS" | while IFS= read -r dll_path; do
  [[ -z "$dll_path" ]] && continue
  dll_name=$(basename "$dll_path")
  cp "$dll_path" "$DLL_STAGING/$dll_name"
  echo "  staged: $dll_name"
done

# ── 3. Stage GLib compiled schemas ───────────────────────────────────────────
echo "[collect-dlls] Compiling GLib schemas..."
SCHEMA_SRC_DIR="$MSYS2_ROOT/share/glib-2.0/schemas"
SCHEMA_STAGING="$STAGING_DIR/share/glib-2.0/schemas"
mkdir -p "$SCHEMA_STAGING"
cp "$SCHEMA_SRC_DIR"/*.xml "$SCHEMA_STAGING/" 2>/dev/null || true
glib-compile-schemas "$SCHEMA_STAGING"
echo "  staged: gschemas.compiled"

# ── 4. Stage GDK-Pixbuf loaders ──────────────────────────────────────────────
echo "[collect-dlls] Staging GDK-Pixbuf loaders..."
PIXBUF_STAGING="$STAGING_DIR/lib/gdk-pixbuf-2.0/2.10.0/loaders"
mkdir -p "$PIXBUF_STAGING"

# Copy loader DLLs
PIXBUF_LIB_DIR="$MSYS2_ROOT/lib/gdk-pixbuf-2.0/2.10.0/loaders"
if [[ -d "$PIXBUF_LIB_DIR" ]]; then
  cp "$PIXBUF_LIB_DIR"/*.dll "$PIXBUF_STAGING/" 2>/dev/null || true
fi

# Generate loaders.cache pointing to installation path
GDK_PIXBUF_MODULEDIR="lib\\gdk-pixbuf-2.0\\2.10.0\\loaders" \
  gdk-pixbuf-query-loaders \
  "$PIXBUF_STAGING"/*.dll \
  > "$STAGING_DIR/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache" 2>/dev/null || true
echo "  staged: loaders.cache"

# ── 5. Convert PNG icon to .ico ───────────────────────────────────────────────
echo "[collect-dlls] Converting icon..."
ICO_OUT="$STAGING_DIR/heelonvault.ico"
# Use ImageMagick to produce a multi-resolution .ico from the 256px PNG
ICON_SRC="assets/icons/hicolor/256x256/apps/heelonvault.png"
if command -v convert >/dev/null 2>&1 && [[ -f "$ICON_SRC" ]]; then
  convert "$ICON_SRC" \
    \( -clone 0 -resize 16x16 \) \
    \( -clone 0 -resize 32x32 \) \
    \( -clone 0 -resize 48x48 \) \
    \( -clone 0 -resize 128x128 \) \
    \( -clone 0 -resize 256x256 \) \
    -delete 0 "$ICO_OUT"
  echo "  staged: heelonvault.ico"
else
  echo "[WARN] ImageMagick not found or icon source missing — .ico skipped"
fi

# ── 6. Generate wix/dlls.wxs ─────────────────────────────────────────────────
echo "[collect-dlls] Generating $OUT_WXS..."
mkdir -p "$(dirname "$OUT_WXS")"

# WiX identifiers allow only: letters, digits, underscore, period.
# They must start with a letter or underscore.
sanitize_wix_id() {
  local raw="$1"
  local sanitized
  sanitized="$(echo "$raw" | sed -E 's/[^A-Za-z0-9_.]/_/g')"
  if [[ ! "$sanitized" =~ ^[A-Za-z_] ]]; then
    sanitized="_$sanitized"
  fi
  echo "$sanitized"
}

cat > "$OUT_WXS" << 'WXSHEADER'
<?xml version="1.0" encoding="UTF-8"?>
<!--
  AUTO-GENERATED by scripts/collect-dlls.sh — DO NOT EDIT MANUALLY
  Regenerate by running the script in a MSYS2 MINGW64 shell.
-->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <ComponentGroup Id="DllComponents" Directory="INSTALLFOLDER">
WXSHEADER

# Emit one Component per DLL
INDEX=0
echo "$DLL_PATHS" | while IFS= read -r dll_path; do
  [[ -z "$dll_path" ]] && continue
  dll_name=$(basename "$dll_path")
  safe_name="$(sanitize_wix_id "$dll_name")"
  safe_id="Dll_${safe_name}_$INDEX"
  guid=$(python3 -c "import uuid; print(str(uuid.uuid5(uuid.NAMESPACE_DNS, '${dll_name}')).upper())" 2>/dev/null || uuidgen | tr '[:lower:]' '[:upper:]')
  cat >> "$OUT_WXS" << DLLCOMP
      <Component Id="${safe_id}" Guid="${guid}">
        <File Id="file_${safe_id}"
              Source="wix\\staging\\${dll_name}"
              KeyPath="yes" />
      </Component>
DLLCOMP
  INDEX=$((INDEX + 1))
done

# Emit GDK-Pixbuf loader DLL components
cat >> "$OUT_WXS" << 'PIXBUFHEADER'
    </ComponentGroup>

    <ComponentGroup Id="PixbufLoaderComponents" Directory="GDKPIXBUF_LOADERS_DIR">
PIXBUFHEADER

PINDEX=0
for loader_dll in "$PIXBUF_STAGING"/*.dll; do
  [[ -f "$loader_dll" ]] || continue
  pname=$(basename "$loader_dll")
  safe_pname="$(sanitize_wix_id "$pname")"
  safe_pid="Pixbuf_${safe_pname}_$PINDEX"
  pguid=$(python3 -c "import uuid; print(str(uuid.uuid5(uuid.NAMESPACE_DNS, 'pixbuf_${pname}')).upper())" 2>/dev/null || uuidgen | tr '[:lower:]' '[:upper:]')
  cat >> "$OUT_WXS" << PIXBUFCOMP
      <Component Id="${safe_pid}" Guid="${pguid}">
        <File Id="file_${safe_pid}"
              Source="wix\\staging\\lib\\gdk-pixbuf-2.0\\2.10.0\\loaders\\${pname}"
              KeyPath="yes" />
      </Component>
PIXBUFCOMP
  PINDEX=$((PINDEX + 1))
done

cat >> "$OUT_WXS" << 'WXSFOOTER'
    </ComponentGroup>
  </Fragment>
</Wix>
WXSFOOTER

echo "[collect-dlls] Done — $OUT_WXS written."
